import type { Project } from './domain.js';
import { supabase } from './cloud.js';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]!);
export function collaborationPage(projects:Project[], href:(s:string)=>string, preview:boolean):string {
  return `<main class="collaboration-page"><a href="${href('/app')}" data-route>← Back to home</a><p class="eyebrow">CREATE TOGETHER</p><h1>Collaborate</h1><p>Bring your crew into a project, or join a story already in motion.</p><div class="collaboration-choices"><button id="choose-invite" type="button"><strong>Invite a teammate</strong><span>Create a six-character code for your project.</span></button><button id="choose-join" type="button"><strong>Join a project</strong><span>Enter the code your project owner shared.</span></button></div><section id="invite-code-panel" hidden><h2>Invite a teammate</h2><p>The code grants an editor seat. It expires after 60 seconds and can be used once. Creating another code replaces the previous one.</p><form id="generate-code"><label>Project<select name="project" required>${projects.map(p=>`<option value="${esc(p.id)}">${esc(p.title)}</option>`).join('')}</select></label><button ${!projects.length||preview?'disabled':''} type="submit">Generate invite code</button></form>${!projects.length?'<p>Create a project first to invite teammates.</p>':''}<div id="generated-code" hidden><output></output><button type="button" id="copy-code">Copy code</button><p id="code-expiry" aria-live="off"></p><button type="button" id="resend-code" hidden>Generate a new code</button></div></section><section id="join-code-panel" hidden><h2>Join a project</h2><form id="join-code"><label>Invite code<input name="code" maxlength="6" minlength="6" pattern="[A-Za-z0-9]{6}" placeholder="A7K2M9" autocomplete="off" autocapitalize="characters" required></label><button type="submit" ${preview?'disabled':''}>Join project</button></form></section><p role="status" id="collaboration-status">${preview?'Sign in to invite teammates or join a project.':''}</p><p class="collaboration-note">Project membership is shared. Tool documents currently save in each person's browser; live document synchronization is not connected yet.</p></main>`;
}
export function wireCollaboration(href:(s:string)=>string, navigate:(s:string)=>void):void {
  const status=document.querySelector<HTMLElement>('#collaboration-status')!;
  for(const mode of ['invite','join']) document.querySelector(`#choose-${mode}`)?.addEventListener('click',()=>{document.querySelector<HTMLElement>('#invite-code-panel')!.hidden=mode!=='invite';document.querySelector<HTMLElement>('#join-code-panel')!.hidden=mode!=='join';});
  const run=async(form:HTMLFormElement,work:()=>Promise<void>)=>{const button=form.querySelector<HTMLButtonElement>('button')!;button.disabled=true;status.textContent='Working…';try{await work();}catch(error){status.textContent=error instanceof Error?error.message:'Please try again.';}finally{button.disabled=false;}};
  let countdown: ReturnType<typeof setInterval> | undefined;
  const generate=document.querySelector<HTMLFormElement>('#generate-code')!;
  generate.onsubmit=event=>{event.preventDefault();void run(generate,async()=>{const {data,error}=await supabase.rpc('generate_project_code',{p_project:String(new FormData(generate).get('project'))});if(error)throw new Error(error.code==='PGRST202'?'Invite codes are awaiting server setup. Please try again later.':error.message);const panel=document.querySelector<HTMLElement>('#generated-code')!;panel.hidden=false;panel.querySelector('output')!.textContent=data.code;clearInterval(countdown); const expiry=Date.parse(data.expiresAt); const resend=document.querySelector<HTMLButtonElement>("#resend-code")!; const copy=document.querySelector<HTMLButtonElement>("#copy-code")!; resend.hidden=true;copy.disabled=false; const tick=()=>{if(!panel.isConnected){clearInterval(countdown);return;}const seconds=Math.max(0,Math.ceil((expiry-Date.now())/1000));document.querySelector("#code-expiry")!.textContent=seconds ? `Expires in ${seconds} seconds` : "This code has expired.";if(!seconds){clearInterval(countdown);resend.hidden=false;copy.disabled=true;}};tick();countdown=setInterval(tick,1000);status.textContent='Share this code with the teammate you want to invite.';});};
  document.querySelector("#resend-code")?.addEventListener("click",()=>generate.requestSubmit());
  const join=document.querySelector<HTMLFormElement>('#join-code')!;
  join.onsubmit=event=>{event.preventDefault();void run(join,async()=>{const {data,error}=await supabase.rpc('join_project_code',{p_code:String(new FormData(join).get('code')).trim().toUpperCase()});if(error)throw new Error(error.code==='PGRST202'?'Invite codes are awaiting server setup. Please try again later.':error.message);if(data.error)throw new Error(data.error);navigate(href(`/app/projects/${data.projectId}`));});};
  document.querySelector('#copy-code')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(document.querySelector('#generated-code output')!.textContent!);status.textContent='Code copied.';}catch{status.textContent='Select and copy the code shown above.';}});
}
