import type { ToolRecord } from './tool-data.js';
const esc = (value: string) => value.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
export function studioDocument(tool: string, record: ToolRecord, projectTitle: string): string {
  const locked = record.fields.published === 'true' && tool === 'call-sheets';
  const field = (key: string, label: string, type = 'text', wide = false) => `<label class="studio-document-field ${wide ? 'wide' : ''}"><span>${label}</span>${type === 'textarea' ? `<textarea name="${key}" rows="3" ${locked ? 'readonly' : ''}>${esc(record.fields[key] || '')}</textarea>` : `<input name="${key}" type="${type}" value="${esc(record.fields[key] || '')}" ${locked ? 'readonly' : ''}>`}</label>`;
  const actions = `<div class="tool-form-actions">${tool === 'call-sheets' ? `<button type="button" id="studio-duplicate">Duplicate draft</button>${!locked ? '<button type="button" id="tool-publish">Publish version</button>' : ''}` : ''}<button type="button" id="tool-print">Print / PDF</button><button type="button" id="tool-remove" class="danger-text">Delete</button></div>`;
  const heading = `<div class="tool-form-header"><label class="tool-title-label">${tool === 'locations' ? 'Location' : tool === 'notes' ? 'Document' : 'Call sheet'}<input name="title" value="${esc(record.title)}" maxlength="160" ${locked ? 'readonly' : ''}></label>${actions}</div>`;
  const stamp = `<dl class="studio-metadata"><dt>Created</dt><dd>${new Date(record.createdAt).toLocaleString()}</dd><dt>Last edited</dt><dd>${new Date(record.updatedAt).toLocaleString()}</dd><dt>Storage</dt><dd>This browser</dd></dl>`;
  if (tool === 'notes') return `<form id="tool-form" class="studio-note-layout"><article class="tool-form studio-note-paper">${heading}<div class="studio-note-properties">${field('folder','Folder')}${field('tags','Tags (comma separated)')}</div><label class="studio-note-body"><span class="sr-only">Document text</span><textarea name="body" placeholder="Start writing your ideas…" aria-label="Document text">${esc(record.fields.body || '')}</textarea></label></article><aside class="studio-detail-panel"><section><h3>Note details</h3>${stamp}</section><section><h3>Pinned checklist</h3>${field('checklist','Tasks — one per line','textarea')}</section><section><h3>Linked references</h3>${field('references','Links and reference notes','textarea')}</section></aside></form>`;
  if (tool === 'locations') {
    const image = /^(https?:\/\/|data:image\/(png|jpeg|webp);base64,)/i.test(record.fields.image || '') ? record.fields.image : '';
    const map = record.fields.address ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.fields.address)}` : '';
    return `<form id="tool-form" class="studio-location-layout"><article class="tool-form">${heading}<div class="studio-location-status"><label>Status<select name="locationStatus">${['Scout','Pending','Confirmed'].map(value => `<option ${record.fields.locationStatus === value ? 'selected' : ''}>${value}</option>`).join('')}</select></label>${map ? `<a href="${esc(map)}" target="_blank" rel="noopener noreferrer">View on Maps ↗</a>` : '<span>Add an address to open its map</span>'}</div><label class="studio-location-photo">${image ? `<img src="${esc(image)}" alt="Location reference">` : '<span>＋ Add a location photo</span>'}<input id="tool-image-file" type="file" accept="image/*" aria-label="Upload location photo"></label><h3>Location details</h3><div class="studio-location-fields">${field('address','Address')}${field('contact','Contact person')}${field('phone','Contact phone','tel')}${field('permit','Permit details')}${field('availability','Available dates and times')}${field('interiorExterior','Interior / exterior')}${field('access','Access & parking','textarea')}${field('power','Power availability','textarea')}${field('sound','Sound conditions','textarea')}${field('travel','Travel and logistics','textarea')}</div></article><aside class="studio-detail-panel"><section><h3>Scenes at this location</h3>${field('scenes','Scene numbers or names','textarea')}</section><section><h3>Notes & checklist</h3>${field('notes','Location notes','textarea')}${field('checklist','Tasks — one per line','textarea')}</section><section><h3>Safety & contingency</h3>${field('safety','Access restrictions and safety notes','textarea')}</section></aside></form>`;
  }
  return `<form id="tool-form" class="studio-call-layout"><article class="tool-form studio-call-paper"><div class="studio-call-masthead"><h2>${esc(projectTitle)}</h2>${field('date','Shoot date','date')}</div>${heading}${locked ? '<p class="tool-published">Published snapshot · This version is read only.</p>' : ''}<div class="studio-call-top"><section><h3>Production</h3>${field('director','Director')}${field('producer','Producer')}${field('upm','Production manager')}${field('location','Location')}${field('address','Address / access')}</section><section class="studio-general-call"><h3>General call</h3>${field('call','Call time','time')}${field('wrap','Estimated wrap','time')}${field('meals','Meals / breaks')}</section><section><h3>Weather & notes</h3>${field('weather','Weather (manual)','textarea')}${field('notes','Notes for today','textarea')}</section></div><div class="studio-call-bottom"><section><h3>Today's schedule</h3>${field('schedule','Time · scene · description · location','textarea')}</section><section><h3>Cast calls</h3>${field('castCalls','Name · character · call time','textarea')}</section><section><h3>Key crew contacts</h3>${field('crewCalls','Role · name · call time','textarea')}</section><section><h3>Locations & moves</h3>${field('moves','Moves / parking','textarea')}</section><section><h3>Safety & contacts</h3>${field('contacts','Emergency contacts','textarea')}${field('hospital','Nearest hospital')}</section></div></article><aside class="studio-detail-panel"><section><h3>Version details</h3><p class="studio-version-badge">${locked ? 'Published' : 'Draft'}</p>${stamp}${locked ? `<p>Published ${new Date(record.fields.publishedAt).toLocaleString()}</p>` : '<p>Publishing locks this version on this device. Duplicate it to make a revised draft.</p>'}<p>Use Print / PDF to share a copy with your crew.</p></section></aside></form>`;
}
