-- Prompt 02 core schema. Run only through a reviewed Supabase migration workflow.
create extension if not exists pgcrypto;
create type public.member_role as enum ('owner','editor');
create type public.plan_tier as enum ('free','premium');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, tier public.plan_tier not null default 'free', created_at timestamptz not null default now());
create table public.owner_identity (singleton boolean primary key default true check (singleton), user_id uuid not null unique references public.profiles(id), created_at timestamptz not null default now());
create table public.projects (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles(id), title text not null check (char_length(title) between 1 and 160), timezone text not null, revision integer not null default 1 check (revision > 0), archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.project_members (project_id uuid not null references public.projects(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, role public.member_role not null, accepted_at timestamptz not null default now(), primary key(project_id,user_id));
create table public.project_invitations (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, invitee_email text not null, role public.member_role not null default 'editor' check(role='editor'), invited_by uuid not null references public.profiles(id), accepted_at timestamptz, revoked_at timestamptz, created_at timestamptz not null default now(), unique(project_id,invitee_email));
create table public.screenplay_drafts (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, title text not null, revision integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.screenplay_blocks (id uuid primary key default gen_random_uuid(), draft_id uuid not null references public.screenplay_drafts(id) on delete cascade, project_id uuid not null references public.projects(id) on delete cascade, kind text not null, content jsonb not null default '{}'::jsonb, ordinal integer not null, revision integer not null default 1, unique(draft_id,ordinal));
create table public.scenes (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, draft_id uuid references public.screenplay_drafts(id) on delete set null, heading text not null, display_number integer not null, unique(project_id,display_number));
create table public.screenplay_comments (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, block_id uuid not null references public.screenplay_blocks(id) on delete cascade, anchor jsonb not null, body text not null, resolved_at timestamptz, created_at timestamptz not null default now());
create table public.notes (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, title text not null, content jsonb not null default '{}'::jsonb, revision integer not null default 1);
create table public.characters (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, name text not null);
create table public.actors (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, name text not null);
create table public.character_actors (character_id uuid references public.characters(id) on delete cascade, actor_id uuid references public.actors(id) on delete cascade, primary key(character_id,actor_id));
create table public.locations (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, name text not null, details jsonb not null default '{}'::jsonb);
create table public.media (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, storage_path text not null unique, content_type text not null, bytes bigint not null check(bytes>=0), checksum text not null, created_at timestamptz not null default now());
create table public.shots (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, scene_id uuid references public.scenes(id) on delete set null, ordinal integer not null, archived_at timestamptz);
create table public.storyboard_frames (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, shot_id uuid references public.shots(id) on delete set null, media_id uuid references public.media(id) on delete set null, ordinal integer not null, archived_at timestamptz);
create table public.shoot_days (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, shooting_date date not null);
create table public.schedule_entries (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, shoot_day_id uuid not null references public.shoot_days(id) on delete cascade, scene_id uuid references public.scenes(id) on delete set null, starts_at timestamptz, ends_at timestamptz);
create table public.call_sheet_versions (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, version integer not null, snapshot jsonb not null, published_at timestamptz, unique(project_id,version));
create table public.audit_log (id bigint generated always as identity primary key, project_id uuid references public.projects(id) on delete cascade, actor_id uuid references public.profiles(id), action text not null, created_at timestamptz not null default now());

create index on public.project_members(user_id,project_id); create index on public.screenplay_blocks(project_id,draft_id); create index on public.scenes(project_id); create index on public.shots(project_id) where archived_at is null; create index on public.storyboard_frames(project_id) where archived_at is null;
create or replace function public.is_member(p uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.project_members where project_id=p and user_id=auth.uid())$$;
create or replace function public.is_owner(p uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.projects where id=p and owner_id=auth.uid())$$;
create or replace function public.provision_owner(target uuid) returns void language plpgsql security definer set search_path=public as $$begin if exists(select 1 from public.owner_identity) then raise exception 'owner already provisioned'; end if; insert into public.owner_identity(user_id) values(target); end$$;
revoke all on function public.provision_owner(uuid) from public,anon,authenticated;
create or replace function public.create_project_limited(p_title text,p_timezone text) returns uuid language plpgsql security definer set search_path=public as $$declare pid uuid; begin if (select tier from public.profiles where id=auth.uid())='free' and exists(select 1 from public.projects where owner_id=auth.uid() and archived_at is null) then raise exception 'free owned project limit reached'; end if; insert into public.projects(owner_id,title,timezone) values(auth.uid(),p_title,p_timezone) returning id into pid; insert into public.project_members(project_id,user_id,role) values(pid,auth.uid(),'owner'); return pid; end$$;
create or replace function public.add_editor_limited(p uuid,u uuid) returns void language plpgsql security definer set search_path=public as $$begin if not public.is_owner(p) then raise exception 'not owner'; end if; if (select count(*) from public.project_members where project_id=p)>=3 then raise exception 'editor seat limit reached'; end if; insert into public.project_members(project_id,user_id,role) values(p,u,'editor'); end$$;
create or replace function public.assert_project_ref(p uuid, child_project uuid) returns boolean language sql immutable as $$select p=child_project$$;
alter table public.profiles enable row level security; alter table public.owner_identity enable row level security;
alter table public.projects enable row level security; alter table public.project_members enable row level security; alter table public.project_invitations enable row level security;
alter table public.screenplay_drafts enable row level security; alter table public.screenplay_blocks enable row level security; alter table public.scenes enable row level security; alter table public.screenplay_comments enable row level security; alter table public.notes enable row level security; alter table public.characters enable row level security; alter table public.actors enable row level security; alter table public.character_actors enable row level security; alter table public.locations enable row level security; alter table public.media enable row level security; alter table public.shots enable row level security; alter table public.storyboard_frames enable row level security; alter table public.shoot_days enable row level security; alter table public.schedule_entries enable row level security; alter table public.call_sheet_versions enable row level security; alter table public.audit_log enable row level security;
create policy "profile self" on public.profiles for select using(id=auth.uid());
create policy "members read" on public.projects for select using(public.is_member(id)); create policy "owners update" on public.projects for update using(public.is_owner(id));
create policy "members read" on public.project_members for select using(public.is_member(project_id)); create policy "owners manage members" on public.project_members for all using(public.is_owner(project_id)) with check(public.is_owner(project_id));
create policy "owners manage invitations" on public.project_invitations for all using(public.is_owner(project_id)) with check(public.is_owner(project_id));
create policy "member_read_character_actors" on public.character_actors for select using(exists(select 1 from public.characters c where c.id=character_id and public.is_member(c.project_id)));
create policy "member_write_character_actors" on public.character_actors for all using(exists(select 1 from public.characters c where c.id=character_id and public.is_member(c.project_id))) with check(exists(select 1 from public.characters c join public.actors a on a.id=actor_id where c.id=character_id and c.project_id=a.project_id and public.is_member(c.project_id)));
-- Apply the same project-member policy to each project-owned table; explicit policies are intentionally generated here.
do $$declare tbl text; begin foreach tbl in array array['screenplay_drafts','screenplay_blocks','scenes','screenplay_comments','notes','characters','actors','locations','media','shots','storyboard_frames','shoot_days','schedule_entries','call_sheet_versions','audit_log'] loop execute format('create policy member_read_%I on public.%I for select using(public.is_member(project_id))',tbl,tbl); execute format('create policy editor_write_%I on public.%I for insert with check(public.is_member(project_id))',tbl,tbl); execute format('create policy editor_update_%I on public.%I for update using(public.is_member(project_id)) with check(public.is_member(project_id))',tbl,tbl); end loop; end$$;
-- Storage: create private bucket manually/with migrations; objects must have name prefix project_id and policies must join project membership before select/insert.
